// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI8LAlxQV4o6BRmxdvobe061hn_kZ1BEs',
    appId: '1:409275596698:web:aaa46d2d01c54dadd6c423',
    messagingSenderId: '409275596698',
    projectId: 'loginappdemo-fc4f5',
    authDomain: 'loginappdemo-fc4f5.firebaseapp.com',
    storageBucket: 'loginappdemo-fc4f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Omt_JasF-X_t4w4UOqfO5GEF3mKL7Qs',
    appId: '1:409275596698:android:5ace0ef064257014d6c423',
    messagingSenderId: '409275596698',
    projectId: 'loginappdemo-fc4f5',
    storageBucket: 'loginappdemo-fc4f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnH1Q7VBe8VgIeI5swuMSLHXNXCweIApg',
    appId: '1:409275596698:ios:ab70fb8d97300c83d6c423',
    messagingSenderId: '409275596698',
    projectId: 'loginappdemo-fc4f5',
    storageBucket: 'loginappdemo-fc4f5.appspot.com',
    iosClientId: '409275596698-d1boj2rkp1878rhomo7vnmcvtkhkjivd.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindemoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnH1Q7VBe8VgIeI5swuMSLHXNXCweIApg',
    appId: '1:409275596698:ios:ab70fb8d97300c83d6c423',
    messagingSenderId: '409275596698',
    projectId: 'loginappdemo-fc4f5',
    storageBucket: 'loginappdemo-fc4f5.appspot.com',
    iosClientId: '409275596698-d1boj2rkp1878rhomo7vnmcvtkhkjivd.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindemoapp',
  );
}
